
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Jul 24 2024 15:37:46 IST (Jul 24 2024 10:07:46 UTC)

// Verification Directory fv/ASTS 

module ASTS(route_number, nickel_in, dime_in, clock, reset, nickel_out,
     dispense);
  input [3:0] route_number;
  input nickel_in, dime_in, clock, reset;
  output nickel_out, dispense;
  wire [3:0] route_number;
  wire nickel_in, dime_in, clock, reset;
  wire nickel_out, dispense;
  wire [6:0] RTH_current_state;
  wire [5:0] RTW_current_state;
  wire [7:0] RF_current_state;
  wire [4:0] RO_current_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_111, n_112, n_113;
  TLATX1 dispense_reg(.G (n_102), .D (n_101), .Q (dispense), .QN
       (UNCONNECTED));
  TLATX1 nickel_out_reg(.G (n_102), .D (n_100), .Q (nickel_out), .QN
       (UNCONNECTED0));
  OAI21XL g4003__8780(.A0 (n_99), .A1 (n_76), .B0 (n_97), .Y (n_101));
  NOR2XL g4017__4296(.A (n_99), .B (n_89), .Y (n_100));
  DFFSHQX1 \RTH_current_state_reg[0] (.SN (n_98), .CK (clock), .D
       (n_96), .Q (RTH_current_state[0]));
  DFFRHQX1 \RTW_current_state_reg[3] (.RN (n_98), .CK (clock), .D
       (n_95), .Q (RTW_current_state[3]));
  OAI2BB1XL g4007__3772(.A0N (n_87), .A1N (n_44), .B0 (n_94), .Y
       (n_97));
  DFFSXL \RTW_current_state_reg[0] (.SN (n_98), .CK (clock), .D (n_93),
       .Q (RTW_current_state[0]), .QN (UNCONNECTED1));
  DFFRHQX1 \RTH_current_state_reg[3] (.RN (n_98), .CK (clock), .D
       (n_83), .Q (RTH_current_state[3]));
  DFFRHQX1 \RTH_current_state_reg[4] (.RN (n_98), .CK (clock), .D
       (n_84), .Q (RTH_current_state[4]));
  OAI21XL g4015__1474(.A0 (n_92), .A1 (n_80), .B0 (n_82), .Y (n_96));
  AOI221XL g4030__4547(.A0 (n_85), .A1 (n_40), .B0 (n_43), .B1 (n_56),
       .C0 (n_75), .Y (n_99));
  DFFRHQXL \RTW_current_state_reg[2] (.RN (n_98), .CK (clock), .D
       (n_90), .Q (RTW_current_state[2]));
  DFFRHQX1 \RF_current_state_reg[4] (.RN (n_98), .CK (clock), .D
       (n_66), .Q (RF_current_state[4]));
  DFFRXL \RF_current_state_reg[3] (.RN (n_98), .CK (clock), .D (n_68),
       .Q (UNCONNECTED2), .QN (RF_current_state[3]));
  DFFRHQX1 \RO_current_state_reg[2] (.RN (n_98), .CK (clock), .D
       (n_63), .Q (RO_current_state[2]));
  DFFRHQX1 \RTH_current_state_reg[2] (.RN (n_98), .CK (clock), .D
       (n_59), .Q (RTH_current_state[2]));
  DFFRXL \RF_current_state_reg[2] (.RN (n_98), .CK (clock), .D (n_62),
       .Q (UNCONNECTED3), .QN (RF_current_state[2]));
  OAI2BB1X1 g4037__9682(.A0N (n_70), .A1N (n_94), .B0 (n_77), .Y
       (n_95));
  DFFRHQX1 \RTW_current_state_reg[4] (.RN (n_98), .CK (clock), .D
       (n_74), .Q (RTW_current_state[4]));
  DFFRHQX1 \RTH_current_state_reg[5] (.RN (n_98), .CK (clock), .D
       (n_58), .Q (RTH_current_state[5]));
  OAI21XL g4041__2683(.A0 (n_92), .A1 (n_88), .B0 (n_71), .Y (n_93));
  OAI32X1 g4016__1309(.A0 (n_28), .A1 (n_86), .A2 (n_33), .B0 (n_92),
       .B1 (n_61), .Y (n_91));
  DFFRHQX1 \RF_current_state_reg[5] (.RN (n_98), .CK (clock), .D
       (n_78), .Q (RF_current_state[5]));
  OAI21XL g4036__6877(.A0 (n_89), .A1 (n_88), .B0 (n_52), .Y (n_90));
  AOI22XL g4035__2900(.A0 (n_29), .A1 (n_86), .B0 (n_41), .B1 (n_85),
       .Y (n_87));
  DFFRHQX1 \RF_current_state_reg[6] (.RN (n_98), .CK (clock), .D
       (n_48), .Q (RF_current_state[6]));
  DFFSX1 \RO_current_state_reg[0] (.SN (n_98), .CK (clock), .D (n_42),
       .Q (UNCONNECTED4), .QN (RO_current_state[0]));
  DFFRHQX1 \RTW_current_state_reg[1] (.RN (n_98), .CK (clock), .D
       (n_50), .Q (RTW_current_state[1]));
  OAI21XL g4040__2391(.A0 (n_89), .A1 (n_81), .B0 (n_55), .Y (n_84));
  OAI21XL g4039__7675(.A0 (n_89), .A1 (n_79), .B0 (n_53), .Y (n_83));
  DFFRHQX1 \RTH_current_state_reg[6] (.RN (n_98), .CK (clock), .D
       (n_112), .Q (RTH_current_state[6]));
  NAND4XL g4046__7118(.A (n_34), .B (n_81), .C (n_80), .D (n_79), .Y
       (n_82));
  DFFRX1 \RF_current_state_reg[1] (.RN (n_98), .CK (clock), .D (n_46),
       .Q (UNCONNECTED5), .QN (RF_current_state[1]));
  DFFRXL \RTH_current_state_reg[1] (.RN (n_98), .CK (clock), .D (n_49),
       .Q (n_16), .QN (RTH_current_state[1]));
  OAI222XL g4026__8757(.A0 (n_89), .A1 (n_67), .B0 (n_92), .B1 (n_47),
       .C0 (n_64), .C1 (n_73), .Y (n_78));
  AOI22X1 g4059__1786(.A0 (n_76), .A1 (n_26), .B0 (nickel_in), .B1
       (n_51), .Y (n_77));
  OAI21XL g4060__5953(.A0 (n_25), .A1 (n_113), .B0 (n_30), .Y (n_75));
  DFFRHQX1 \RO_current_state_reg[3] (.RN (n_98), .CK (clock), .D
       (n_36), .Q (RO_current_state[3]));
  DFFRHQX1 \RTW_current_state_reg[5] (.RN (n_98), .CK (clock), .D
       (n_31), .Q (RTW_current_state[5]));
  OAI22XL g4062__5703(.A0 (n_89), .A1 (n_69), .B0 (n_73), .B1 (n_113),
       .Y (n_74));
  DFFRHQX1 \RO_current_state_reg[1] (.RN (n_98), .CK (clock), .D
       (n_37), .Q (RO_current_state[1]));
  DFFRHQX1 \RF_current_state_reg[7] (.RN (n_98), .CK (clock), .D
       (n_32), .Q (RF_current_state[7]));
  NAND4BXL g4067__7114(.AN (n_70), .B (n_113), .C (n_69), .D (n_88), .Y
       (n_71));
  OAI222XL g4042__5266(.A0 (n_92), .A1 (n_67), .B0 (n_89), .B1 (n_60),
       .C0 (n_65), .C1 (n_73), .Y (n_68));
  OAI222XL g4043__2250(.A0 (n_89), .A1 (n_65), .B0 (n_92), .B1 (n_64),
       .C0 (n_67), .C1 (n_73), .Y (n_66));
  OAI21XL g4038__6083(.A0 (n_89), .A1 (n_39), .B0 (n_38), .Y (n_63));
  OAI222XL g4044__2703(.A0 (n_89), .A1 (n_61), .B0 (n_92), .B1 (n_65),
       .C0 (n_60), .C1 (n_73), .Y (n_62));
  OAI222XL g4045__5795(.A0 (n_89), .A1 (n_80), .B0 (n_92), .B1 (n_81),
       .C0 (n_79), .C1 (n_73), .Y (n_59));
  INVXL g4047(.A (n_57), .Y (n_58));
  AOI22XL g4054__7344(.A0 (n_94), .A1 (n_54), .B0 (n_56), .B1
       (nickel_in), .Y (n_57));
  AOI22X1 g4053__1840(.A0 (n_76), .A1 (n_56), .B0 (nickel_in), .B1
       (n_54), .Y (n_55));
  AOI2BB2X1 g4052__5019(.A0N (n_73), .A1N (n_81), .B0 (n_76), .B1
       (n_54), .Y (n_53));
  AOI22X1 g4055__1857(.A0 (n_76), .A1 (n_51), .B0 (nickel_in), .B1
       (n_70), .Y (n_52));
  OAI2BB2XL g4058__9906(.A0N (n_70), .A1N (n_76), .B0 (n_73), .B1
       (n_88), .Y (n_50));
  OAI22X1 g4064__8780(.A0 (n_92), .A1 (n_79), .B0 (n_73), .B1 (n_80),
       .Y (n_49));
  OAI22XL g4065__4296(.A0 (n_89), .A1 (n_64), .B0 (n_73), .B1 (n_47),
       .Y (n_48));
  OAI22X1 g4066__3772(.A0 (n_92), .A1 (n_60), .B0 (n_73), .B1 (n_61),
       .Y (n_46));
  AOI22XL g4061__4547(.A0 (n_43), .A1 (n_54), .B0 (n_51), .B1 (n_13),
       .Y (n_44));
  OAI32X1 g4028__9682(.A0 (n_41), .A1 (n_40), .A2 (n_14), .B0 (n_92),
       .B1 (n_39), .Y (n_42));
  DFFRHQX1 \RO_current_state_reg[4] (.RN (n_98), .CK (clock), .D
       (n_24), .Q (RO_current_state[4]));
  AOI22X1 g4057__2683(.A0 (n_76), .A1 (n_40), .B0 (nickel_in), .B1
       (n_41), .Y (n_38));
  OAI22X1 g4056__1309(.A0 (n_92), .A1 (n_35), .B0 (n_73), .B1 (n_39),
       .Y (n_37));
  OAI2BB2XL g4063__6877(.A0N (n_40), .A1N (nickel_in), .B0 (n_89), .B1
       (n_35), .Y (n_36));
  NOR2XL g4069__2900(.A (n_54), .B (n_56), .Y (n_34));
  NAND2X1 g4071__2391(.A (n_65), .B (n_61), .Y (n_33));
  NOR2XL g4076__7675(.A (n_89), .B (n_47), .Y (n_32));
  NOR2XL g4073__7118(.A (n_89), .B (n_113), .Y (n_31));
  NAND2BXL g4074__8757(.AN (n_47), .B (n_29), .Y (n_30));
  NAND2X1 g4075__1786(.A (n_47), .B (n_60), .Y (n_28));
  NAND2X1 g4072__5953(.A (n_67), .B (n_64), .Y (n_86));
  INVX1 g4094(.A (n_51), .Y (n_69));
  INVXL g4095(.A (n_113), .Y (n_26));
  NAND3XL g4029__5703(.A (n_25), .B (n_10), .C (n_15), .Y (n_102));
  NOR2XL g4077__7114(.A (n_89), .B (n_11), .Y (n_24));
  NAND4BXL g4082__5266(.AN (RF_current_state[3]), .B (n_23), .C (n_22),
       .D (RF_current_state[2]), .Y (n_67));
  NAND4BXL g4101__2250(.AN (RTH_current_state[2]), .B (n_21), .C
       (RTH_current_state[1]), .D (RTH_current_state[0]), .Y (n_80));
  NAND4BXL g4083__6083(.AN (RF_current_state[2]), .B (n_23), .C (n_22),
       .D (RF_current_state[3]), .Y (n_65));
  NAND4X1 g4085__2703(.A (n_23), .B (n_12), .C (RF_current_state[1]),
       .D (n_111), .Y (n_61));
  NOR4BX1 g4105__7344(.AN (RTW_current_state[2]), .B (n_20), .C
       (RTW_current_state[1]), .D (RTW_current_state[3]), .Y (n_51));
  NAND4BXL g4086__1840(.AN (RF_current_state[5]), .B (n_19), .C (n_18),
       .D (RF_current_state[4]), .Y (n_64));
  NAND4BXL g4102__5019(.AN (RTH_current_state[0]), .B (n_21), .C
       (RTH_current_state[1]), .D (RTH_current_state[2]), .Y (n_81));
  NOR4BX1 g4099__1857(.AN (RTW_current_state[1]), .B (n_20), .C
       (RTW_current_state[2]), .D (RTW_current_state[3]), .Y (n_70));
  NAND4BXL g4090__9906(.AN (RF_current_state[4]), .B (n_19), .C (n_18),
       .D (RF_current_state[5]), .Y (n_47));
  NOR4BX1 g4089__8780(.AN (RTH_current_state[4]), .B (n_17), .C (n_16),
       .D (RTH_current_state[3]), .Y (n_56));
  NOR4BX1 g4088__4296(.AN (RTH_current_state[3]), .B (n_17), .C (n_16),
       .D (RTH_current_state[4]), .Y (n_54));
  INVXL g4091(.A (n_15), .Y (n_85));
  INVX1 g4093(.A (n_35), .Y (n_41));
  INVX1 g4092(.A (n_14), .Y (n_39));
  INVXL g4078(.A (n_25), .Y (n_13));
  NAND3X1 g4084__3772(.A (n_23), .B (n_0), .C (n_12), .Y (n_60));
  INVX1 g4096(.A (n_11), .Y (n_40));
  NAND3X1 g4103__1474(.A (n_21), .B (n_5), .C (n_16), .Y (n_79));
  NOR2XL g4068__4547(.A (n_43), .B (n_29), .Y (n_10));
  NAND3BXL g4097__9682(.AN (route_number[1]), .B (n_7), .C
       (route_number[0]), .Y (n_15));
  NAND4BXL g4107__2683(.AN (RO_current_state[1]), .B (n_8), .C
       (RO_current_state[2]), .D (RO_current_state[0]), .Y (n_11));
  NOR4BX1 g4100__1309(.AN (n_8), .B (RO_current_state[2]), .C
       (RO_current_state[1]), .D (RO_current_state[0]), .Y (n_14));
  NAND3BXL g4080__6877(.AN (route_number[0]), .B (n_7), .C
       (route_number[1]), .Y (n_25));
  NAND4BXL g4104__2900(.AN (RO_current_state[2]), .B (n_8), .C
       (RO_current_state[0]), .D (RO_current_state[1]), .Y (n_35));
  NAND4BXL g4087__2391(.AN (RTW_current_state[3]), .B (n_6), .C (n_4),
       .D (RTW_current_state[0]), .Y (n_88));
  NAND2X1 g4108__7675(.A (n_5), .B (n_3), .Y (n_17));
  AND2X2 g4109__7118(.A (n_12), .B (n_22), .Y (n_19));
  NAND2BX1 g4111__8757(.AN (RTW_current_state[0]), .B (n_4), .Y (n_20));
  AND2X2 g4112__1786(.A (n_2), .B (n_3), .Y (n_21));
  INVX1 g4114(.A (n_89), .Y (n_94));
  AND2X2 g4113__5953(.A (n_1), .B (n_18), .Y (n_23));
  INVX2 g4122(.A (n_76), .Y (n_92));
  NAND2X2 g4121__5703(.A (n_73), .B (dime_in), .Y (n_89));
  NOR4BXL g4081__7114(.AN (route_number[2]), .B (route_number[0]), .C
       (route_number[1]), .D (route_number[3]), .Y (n_43));
  NOR4BXL g4098__5266(.AN (route_number[3]), .B (route_number[0]), .C
       (route_number[1]), .D (route_number[2]), .Y (n_29));
  NOR2X1 g4116__2250(.A (RTH_current_state[3]), .B
       (RTH_current_state[4]), .Y (n_2));
  NOR2X1 g4125__6083(.A (RTW_current_state[5]), .B
       (RTW_current_state[4]), .Y (n_4));
  NOR2X1 g4119__2703(.A (RTH_current_state[2]), .B
       (RTH_current_state[0]), .Y (n_5));
  NOR2X1 g4127__5795(.A (RF_current_state[6]), .B
       (RF_current_state[7]), .Y (n_18));
  NOR2BX1 g4126__7344(.AN (RF_current_state[1]), .B (n_111), .Y (n_22));
  NOR2X2 g4129__1840(.A (nickel_in), .B (dime_in), .Y (n_76));
  NOR2X1 g4123__5019(.A (RF_current_state[4]), .B
       (RF_current_state[5]), .Y (n_1));
  NOR2X1 g4115__1857(.A (RF_current_state[1]), .B (n_111), .Y (n_0));
  NOR2XL g4124__9906(.A (route_number[3]), .B (route_number[2]), .Y
       (n_7));
  NOR2X1 g4117__8780(.A (RTW_current_state[1]), .B
       (RTW_current_state[2]), .Y (n_6));
  NOR2X1 g4118__4296(.A (RTH_current_state[5]), .B
       (RTH_current_state[6]), .Y (n_3));
  NOR2X1 g4128__3772(.A (RO_current_state[3]), .B
       (RO_current_state[4]), .Y (n_8));
  AND2X2 g4120__1474(.A (RF_current_state[3]), .B
       (RF_current_state[2]), .Y (n_12));
  INVX4 g4130(.A (nickel_in), .Y (n_73));
  INVXL g4132(.A (reset), .Y (n_98));
  DFFSX1 \RF_current_state_reg[0] (.SN (n_98), .CK (clock), .D (n_91),
       .Q (n_111), .QN (UNCONNECTED6));
  NOR2BX1 g2(.AN (n_56), .B (n_89), .Y (n_112));
  NAND3BX1 g4163(.AN (n_20), .B (n_6), .C (RTW_current_state[3]), .Y
       (n_113));
endmodule

